---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: Check active galaxy config
      command: ansible-config dump | grep GALAXY
      register: galaxy_cfg

    - debug:
        var: galaxy_cfg.stdout_lines

    - name: Install VMware collection
      command: >
        ansible-galaxy collection install community.vmware -vvv
      register: install_test
      ignore_errors: true

    - debug:
        var: install_test.stdout_lines

    - debug:
        var: install_test.stderr_lines
