---
- name: Use Case 2 - Right-Sizer Watchdog (GCP Official & Safe)
  hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    location: "global"
    report_file: "/tmp/gcp_rightsizer_report.json"

  tasks:

  # =====================================================
  # COLLECT RECOMMENDATIONS (OFFICIAL GCP AI)
  # =====================================================

  - name: Collect VM rightsizing recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_rightsizing_raw
    changed_when: false
    failed_when: false

  - name: Collect idle image recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.image.IdleResourceRecommender
      --format=json
    register: idle_image_raw
    changed_when: false
    failed_when: false

  - name: Collect idle disk recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.disk.IdleResourceRecommender
      --format=json
    register: idle_disk_raw
    changed_when: false
    failed_when: false

  # =====================================================
  # SAFE JSON NORMALIZATION (NO PARSE ERROR)
  # =====================================================

  - name: Normalize recommendation outputs safely
    set_fact:
      vm_rightsizing: >-
        {{
          (vm_rightsizing_raw.stdout | trim | length > 0)
          | ternary(vm_rightsizing_raw.stdout | from_json, [])
        }}
      idle_images: >-
        {{
          (idle_image_raw.stdout | trim | length > 0)
          | ternary(idle_image_raw.stdout | from_json, [])
        }}
      idle_disks: >-
        {{
          (idle_disk_raw.stdout | trim | length > 0)
          | ternary(idle_disk_raw.stdout | from_json, [])
        }}

  # =====================================================
  # SUMMARY (WHAT MANAGEMENT CARES ABOUT)
  # =====================================================

  - name: Build recommendation summary
    set_fact:
      summary:
        vm_rightsizing_count: "{{ vm_rightsizing | length }}"
        idle_image_count: "{{ idle_images | length }}"
        idle_disk_count: "{{ idle_disks | length }}"

  # =====================================================
  # FINAL REPORT
  # =====================================================

  - name: Generate Right-Sizer Watchdog report
    copy:
      dest: "{{ report_file }}"
      content: |
        {{
          {
            "project": project_id,
            "generated_at": lookup('pipe','date -Is'),
            "use_case": "Right-Sizer Watchdog",
            "summary": summary,
            "recommendations": {
              "vm_rightsizing": vm_rightsizing,
              "idle_images": idle_images,
              "idle_disks": idle_disks
            },
            "notes": [
              "Data source: GCP Recommender API (official)",
              "PVC-level idle detection is not available via API",
              "This report is advisory; no automatic changes applied"
            ]
          } | to_nice_json
        }}

  # =====================================================
  # EXPORT (AAP / CI)
  # =====================================================

  - name: Export report as job artifact
    set_stats:
      data:
        gcp_rightsizer_report: "{{ lookup('file', report_file) }}"

  - name: Show summary
    debug:
      msg:
        - "VM rightsizing recommendations: {{ summary.vm_rightsizing_count }}"
        - "Idle images: {{ summary.idle_image_count }}"
        - "Idle disks: {{ summary.idle_disk_count }}"
