---
- name: Use Case 2 - Right-Sizer Watchdog (GCP Official & Safe)
  hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    location: "global"
    report_file: "/tmp/gcp_rightsizer_report.json"

  tasks:

  # ================================
  # COLLECT RECOMMENDATIONS (RAW)
  # ================================

  - name: Collect VM rightsizing recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_rightsizing_raw
    changed_when: false
    failed_when: false

  - name: Collect idle image recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.image.IdleResourceRecommender
      --format=json
    register: idle_image_raw
    changed_when: false
    failed_when: false

  - name: Collect idle disk recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.disk.IdleResourceRecommender
      --format=json
    register: idle_disk_raw
    changed_when: false
    failed_when: false

  # ================================
  # BUILD REPORT (NO PARSING)
  # ================================

  - name: Build Right-Sizer Watchdog report (safe)
    copy:
      dest: "{{ report_file }}"
      content: |
        {
          "project": "{{ project_id }}",
          "generated_at": "{{ lookup('pipe','date -Is') }}",
          "use_case": "Right-Sizer Watchdog (collect only)",
          "recommendations": {
            "vm_rightsizing": {{ vm_rightsizing_raw.stdout | default('[]') }},
            "idle_images": {{ idle_image_raw.stdout | default('[]') }},
            "idle_disks": {{ idle_disk_raw.stdout | default('[]') }}
          },
          "notes": [
            "Data collected using official GCP Recommender API",
            "No JSON parsing performed inside Ansible (safe for AAP)",
            "Apply / resize actions must be a separate job"
          ]
        }

  - name: Export report as AAP Job Artifact
    set_stats:
      data:
        gcp_rightsizer_report: "{{ lookup('file', report_file) }}"
