---
- name: Demo 1 - GCP Right-Sizer Watchdog (Collect Only)
  hosts: localhost
  gather_facts: false

  vars:
    project_id: joey-preprod-project
    location: global
    report_file: /tmp/gcp_rightsizer_collect.json

  tasks:

  - name: Collect VM rightsizing recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_rightsizing
    changed_when: false
    failed_when: false

  - name: Collect idle image recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.image.IdleResourceRecommender
      --format=json
    register: idle_image
    changed_when: false
    failed_when: false

  - name: Collect idle disk recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.disk.IdleResourceRecommender
      --format=json
    register: idle_disk
    changed_when: false
    failed_when: false

  - name: Collect GKE cluster inventory
    command: >
      gcloud container clusters list
      --project {{ project_id }}
      --format=json
    register: gke_clusters
    changed_when: false
    failed_when: false

  - name: Build report
    copy:
      dest: "{{ report_file }}"
      content: |
        {{
          {
            "project": project_id,
            "generated_at": lookup('pipe','date -Is'),
            "recommendations": {
              "vm_rightsizing": vm_rightsizing.stdout | default('[]') | from_json,
              "idle_images": idle_image.stdout | default('[]') | from_json,
              "idle_disks": idle_disk.stdout | default('[]') | from_json
            },
            "gke_clusters": gke_clusters.stdout | default('[]') | from_json,
            "notes": [
              "Low usage detected via Recommender AI",
              "High usage metrics not included in this demo",
              "PVC visibility is not supported via gcloud"
            ]
          } | to_nice_json
        }}

  - name: Export report
    set_stats:
      data:
        gcp_rightsizer_collect: "{{ lookup('file', report_file) }}"
