---
- name: Use Case 2 - Right-Sizer Watchdog (GCP Native Only)
  hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    location: "global"
    report_file: "/tmp/gcp_rightsizer_report.json"

  tasks:

  # =====================================================
  # RECOMMENDER API (OFFICIAL & SUPPORTED)
  # =====================================================

  - name: VM rightsizing recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_rightsizing
    failed_when: false
    changed_when: false

  - name: Idle image recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.image.IdleResourceRecommender
      --format=json
    register: idle_image
    failed_when: false
    changed_when: false

  - name: Idle persistent disk recommendations (includes GKE orphan disks)
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ location }}
      --recommender google.compute.disk.IdleResourceRecommender
      --format=json
    register: idle_disk
    failed_when: false
    changed_when: false

  # =====================================================
  # GKE CLUSTER INVENTORY (NO KUBECONFIG)
  # =====================================================

  - name: List GKE clusters
    command: >
      gcloud container clusters list
      --project {{ project_id }}
      --format=json
    register: gke_clusters
    failed_when: false
    changed_when: false

  # =====================================================
  # SAFE NORMALIZATION
  # =====================================================

  - name: Normalize outputs
    set_fact:
      vm_rightsizing_json: "{{ vm_rightsizing.stdout | default('[]') | from_json }}"
      idle_image_json: "{{ idle_image.stdout | default('[]') | from_json }}"
      idle_disk_json: "{{ idle_disk.stdout | default('[]') | from_json }}"
      gke_clusters_json: "{{ gke_clusters.stdout | default('[]') | from_json }}"

  # =====================================================
  # FINAL REPORT
  # =====================================================

  - name: Build Right-Sizer Watchdog report
    copy:
      dest: "{{ report_file }}"
      content: |
        {{
          {
            "project": project_id,
            "generated_at": lookup('pipe','date -Is'),
            "use_case": "Right-Sizer Watchdog (GCP Native)",
            "recommendations": {
              "vm_rightsizing": vm_rightsizing_json,
              "idle_images": idle_image_json,
              "idle_disks": idle_disk_json
            },
            "gke_context": {
              "clusters": gke_clusters_json,
              "note": "PVC-level visibility requires kubeconfig and Kubernetes API access"
            },
            "explicit_limitations": [
              "PVC objects are not accessible via gcloud",
              "PVC idle metrics are not exposed via Recommender API",
              "This automation is advisory, not destructive"
            ]
          } | to_nice_json
        }}

  - name: Export as AAP Job Artifact
    set_stats:
      data:
        gcp_rightsizer_report: "{{ lookup('file', report_file) }}"
