- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    teams_webhook_url: "https://outlook.office.com/webhook/XXXXX"

  tasks:

  ###############################################################
  # AUTHENTICATION
  ###############################################################

  - name: Write GCP Service Account JSON
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # GET CURRENT MACHINE TYPE
  ###############################################################

  - name: Get current machine type
    command: >
      gcloud compute instances describe {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
      --format="value(machineType)"
    register: current_type
    changed_when: false

  - name: Extract current machine type
    set_fact:
      current_machine_type: "{{ current_type.stdout.split('/')[-1] }}"

  ###############################################################
  # AUDIT LOG
  ###############################################################

  - name: Audit log
    debug:
      msg:
        - "ACTION: VM Resize"
        - "Instance: {{ instance }}"
        - "Zone: {{ zone }}"
        - "Current: {{ current_machine_type }}"
        - "Target: {{ machine_type }}"
        - "Approved by: {{ approved_by }}"

  ###############################################################
  # RESIZE IF NEEDED
  ###############################################################

  - name: Stop VM
    command: >
      gcloud compute instances stop {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: current_machine_type != machine_type

  - name: Resize VM
    command: >
      gcloud compute instances set-machine-type {{ instance }}
      --machine-type {{ machine_type }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: current_machine_type != machine_type

  - name: Start VM
    command: >
      gcloud compute instances start {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: current_machine_type != machine_type

  ###############################################################
  # RESULT
  ###############################################################

  - name: Set result
    set_fact:
      resize_status: >-
        {{
          "NO CHANGE - Already " + machine_type
          if current_machine_type == machine_type
          else
          "SUCCESS - Resized from " + current_machine_type + " to " + machine_type
        }}

  - name: Send result to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: |
          VM RESIZE RESULT
          Instance: {{ instance }}
          Zone: {{ zone }}
          Old Type: {{ current_machine_type }}
          New Type: {{ machine_type }}
          Approved By: {{ approved_by }}
          Status: {{ resize_status }}
