- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    teams_webhook_url: "https://outlook.office.com/webhook/XXXXX"

  tasks:

  ###############################################################
  # AUTH
  ###############################################################

  - name: Write GCP Service Account JSON
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # GET CURRENT MACHINE TYPE
  ###############################################################

  - name: Get current machine type
    command: >
      gcloud compute instances describe {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
      --format="value(machineType)"
    register: current_raw
    changed_when: false

  - name: Extract machine types
    set_fact:
      current_machine_type: "{{ current_raw.stdout.split('/')[-1] }}"
      current_cpu: "{{ current_raw.stdout.split('/')[-1].split('-')[-1] | int }}"
      target_cpu: "{{ machine_type.split('-')[-1] | int }}"

  ###############################################################
  # DECISION LOGIC
  ###############################################################

  - name: Decide if downsize allowed
    set_fact:
      allow_resize: "{{ target_cpu < current_cpu }}"

  - name: Debug decision
    debug:
      msg:
        - "Current Type: {{ current_machine_type }}"
        - "Target Type: {{ machine_type }}"
        - "Current CPU: {{ current_cpu }}"
        - "Target CPU: {{ target_cpu }}"
        - "Downsize Allowed: {{ allow_resize }}"

  - name: Block upscale or lateral resize in PROD
    fail:
      msg: >
        Resize blocked.
        Current CPU: {{ current_cpu }}
        Target CPU: {{ target_cpu }}
        Only downsize allowed in production.
    when: not allow_resize


  ###############################################################
  # RESIZE ONLY IF DOWNSIZE
  ###############################################################

  - name: Stop VM
    command: >
      gcloud compute instances stop {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: allow_resize

  - name: Resize VM
    command: >
      gcloud compute instances set-machine-type {{ instance }}
      --machine-type {{ machine_type }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: allow_resize

  - name: Start VM
    command: >
      gcloud compute instances start {{ instance }}
      --zone {{ zone }}
      --project {{ project_id }}
    when: allow_resize

  ###############################################################
  # RESULT
  ###############################################################

  - name: Set result
    set_fact:
      resize_status: >-
        {{
          "SKIPPED - Not a downsize operation"
          if not allow_resize
          else
          "SUCCESS - Downsized from " + current_machine_type + " to " + machine_type
        }}

  - name: Send result to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: |
          VM LOW USAGE REMEDIATION
          Instance: {{ instance }}
          Old Type: {{ current_machine_type }}
          Target: {{ machine_type }}
          Approved By: {{ approved_by }}
          Status: {{ resize_status }}
