- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"
    dry_run: true   # SAFE MODE

  tasks:

  ###############################################################
  # CREATE SERVICE ACCOUNT FILE
  ###############################################################

  - name: Write GCP Service Account JSON
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false


  ###############################################################
  # GET VM RECOMMENDATIONS
  ###############################################################

  - name: Get VM recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ zone }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_recs_raw
    changed_when: false
    failed_when: false

  - name: Set VM list
    set_fact:
      vm_recs: "{{ vm_recs_raw.stdout | from_json }}"
    when: vm_recs_raw.stdout | length > 0


  ###############################################################
  # PROCESS VM DOWNSIZE ONLY
  ###############################################################

  - name: Get current machine type
    command: >
      gcloud compute instances describe {{
      item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}
      --zone {{ zone }}
      --project {{ project_id }}
      --format="value(machineType)"
    register: current_type_raw
    loop: "{{ vm_recs | default([]) }}"
    loop_control:
      label: "{{ item.name }}"
    changed_when: false

  - name: Evaluate VM downsizing
    vars:
      instance_name: "{{ item.item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_machine_type: "{{ item.item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1] }}"
      current_machine_type: "{{ item.stdout.split('/')[-1] }}"
      current_cpu: "{{ item.stdout.split('/')[-1].split('-')[-1] | int }}"
      target_cpu: "{{ target_machine_type.split('-')[-1] | int }}"
    loop: "{{ current_type_raw.results | default([]) }}"
    loop_control:
      label: "{{ instance_name }}"
    block:

      - name: Show downsize plan
        when: target_cpu < current_cpu
        debug:
          msg: >
            DOWNSIZE VM {{ instance_name }}
            ({{ current_machine_type }} → {{ target_machine_type }})

      - name: Stop instance
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud compute instances stop {{ instance_name }}
          --zone {{ zone }}
          --project {{ project_id }}

      - name: Resize instance
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud compute instances set-machine-type {{ instance_name }}
          --machine-type {{ target_machine_type }}
          --zone {{ zone }}
          --project {{ project_id }}

      - name: Start instance
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud compute instances start {{ instance_name }}
          --zone {{ zone }}
          --project {{ project_id }}

      - name: Mark VM recommendation succeeded
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud recommender recommendations mark-succeeded {{ item.item.name }}
          --project {{ project_id }}
          --location {{ zone }}


  ###############################################################
  # GET SQL RECOMMENDATIONS
  ###############################################################

  - name: Get SQL recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ region }}
      --recommender google.cloudsql.instance.PerformanceRecommender
      --format=json
    register: sql_recs_raw
    changed_when: false
    failed_when: false

  - name: Set SQL list
    set_fact:
      sql_recs: "{{ sql_recs_raw.stdout | from_json }}"
    when: sql_recs_raw.stdout | length > 0


  ###############################################################
  # PROCESS SQL DOWNSIZE ONLY
  ###############################################################

  - name: Get current SQL tier
    command: >
      gcloud sql instances describe {{
      item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}
      --project {{ project_id }}
      --format="value(settings.tier)"
    register: current_sql_raw
    loop: "{{ sql_recs | default([]) }}"
    changed_when: false

  - name: Evaluate SQL downsizing
    vars:
      sql_instance: "{{ item.item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_tier: "{{ item.item.content.operationGroups[0].operations[0].value.settings.tier }}"
      current_tier: "{{ item.stdout }}"
      current_cpu: "{{ current_tier.split('-')[2] | int }}"
      target_cpu: "{{ target_tier.split('-')[2] | int }}"
    loop: "{{ current_sql_raw.results | default([]) }}"
    loop_control:
      label: "{{ sql_instance }}"
    block:

      - name: Show SQL downsize plan
        when: target_cpu < current_cpu
        debug:
          msg: >
            DOWNSIZE SQL {{ sql_instance }}
            ({{ current_tier }} → {{ target_tier }})

      - name: Patch SQL
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud sql instances patch {{ sql_instance }}
          --tier={{ target_tier }}
          --project {{ project_id }}
          --quiet

      - name: Mark SQL recommendation succeeded
        when:
          - not dry_run
          - target_cpu < current_cpu
        command: >
          gcloud recommender recommendations mark-succeeded {{ item.item.name }}
          --project {{ project_id }}
          --location {{ region }}
