- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"

    teams_webhook_url: "https://outlook.office.com/webhook/XXXXX"   # GANTI webhook kamu

  tasks:

  ###############################################################
  # AUTHENTICATION
  ###############################################################

  - name: Write GCP Service Account JSON
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # VM MACHINE TYPE RECOMMENDATIONS
  ###############################################################

  - name: Get VM MachineType recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ zone }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_raw
    changed_when: false
    failed_when: false

  - name: Parse VM recommendations
    set_fact:
      vm_recs: "{{ vm_raw.stdout | from_json }}"
    when:
      - vm_raw.stdout is defined
      - vm_raw.stdout | length > 0

  ###############################################################
  # CLOUD SQL PERFORMANCE RECOMMENDATIONS
  ###############################################################

  - name: Get Cloud SQL recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ region }}
      --recommender google.cloudsql.instance.PerformanceRecommender
      --format=json
    register: sql_raw
    changed_when: false
    failed_when: false

  - name: Parse SQL recommendations
    set_fact:
      sql_recs: "{{ sql_raw.stdout | from_json }}"
    when:
      - sql_raw.stdout is defined
      - sql_raw.stdout | length > 0

  ###############################################################
  # BUILD VM REPORT
  ###############################################################

  - name: Initialize VM report
    set_fact:
      vm_report: []

  - name: Build VM report
    loop: "{{ vm_recs | default([]) }}"
    loop_control:
      index_var: idx
    vars:
      instance_name: "{{ item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_machine_type: "{{ item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1] }}"
    set_fact:
      vm_report: "{{ vm_report + [ {
        'id': 'VM-' ~ (idx + 1),
        'instance': instance_name,
        'suggested': target_machine_type
      } ] }}"

  ###############################################################
  # BUILD SQL REPORT
  ###############################################################

  - name: Initialize SQL report
    set_fact:
      sql_report: []

  - name: Build SQL report
    loop: "{{ sql_recs | default([]) }}"
    loop_control:
      index_var: idx
    vars:
      sql_instance: "{{ item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_tier: "{{ item.content.operationGroups[0].operations[0].value.settings.tier }}"
    set_fact:
      sql_report: "{{ sql_report + [ {
        'id': 'SQL-' ~ (idx + 1),
        'instance': sql_instance,
        'suggested': target_tier
      } ] }}"

  ###############################################################
  # FORMAT TEAMS MESSAGE
  ###############################################################

  - name: Build Teams message
    set_fact:
      teams_message: |
        GCP LOW USAGE REPORT
        Project : {{ project_id }}

        === VM RECOMMENDATIONS ===
        {% if vm_report | length == 0 %}
        No VM resize recommendations.
        {% else %}
        {% for v in vm_report %}
        [{{ v.id }}]
        Instance : {{ v.instance }}
        Suggested: {{ v.suggested }}

        {% endfor %}
        {% endif %}

        === CLOUD SQL RECOMMENDATIONS ===
        {% if sql_report | length == 0 %}
        No Cloud SQL resize recommendations.
        {% else %}
        {% for s in sql_report %}
        [{{ s.id }}]
        Instance : {{ s.instance }}
        Suggested Tier: {{ s.suggested }}

        {% endfor %}
        {% endif %}

        Next Action:
        Open AAP → Launch "Remediate Low Usage"
        Fill survey accordingly.

  ###############################################################
  # SEND TO TEAMS
  ###############################################################

  - name: Send report to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: "{{ teams_message }}"
