- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"
    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/7c04326d37a64089badfcd62f0176737/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=8PTg2NuHVi98-k2cTNCYG6AVuw_5e-X_UFYsbtzlEog"

  tasks:

  ###############################################################
  # AUTHENTICATION
  ###############################################################

  - name: Write GCP SA
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false


  ###############################################################
  # VM RECOMMENDATIONS
  ###############################################################

  - name: Get VM MachineType recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ zone }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_raw
    changed_when: false
    failed_when: false

  - name: Parse VM recommendations safely
    set_fact:
      vm_recs: "{{ vm_raw.stdout | default('[]') | from_json }}"

  - name: Initialize VM report
    set_fact:
      vm_report: []

  - name: Get current VM machine types
    command: >
      gcloud compute instances describe {{
      item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}
      --zone {{ zone }}
      --project {{ project_id }}
      --format="value(machineType)"
    register: vm_current_raw
    loop: "{{ vm_recs }}"
    changed_when: false

  - name: Evaluate and append downsize VMs
    loop: "{{ vm_current_raw.results }}"
    loop_control:
      index_var: idx
    vars:
      instance_name: "{{ item.item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_machine_type: "{{ item.item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1] }}"
      current_machine_type: "{{ item.stdout.split('/')[-1] }}"
      current_cpu: "{{ current_machine_type.split('-')[-1] | int }}"
      target_cpu: "{{ target_machine_type.split('-')[-1] | int }}"
    set_fact:
      vm_report: "{{ vm_report + [ {
        'id': 'VM-' ~ (idx + 1),
        'instance': instance_name,
        'current': current_machine_type,
        'suggested': target_machine_type
      } ] }}"
    when: target_cpu < current_cpu


  ###############################################################
  # CLOUD SQL RECOMMENDATIONS
  ###############################################################

  - name: Get Cloud SQL recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ region }}
      --recommender google.cloudsql.instance.PerformanceRecommender
      --format=json
    register: sql_raw
    changed_when: false
    failed_when: false

  - name: Parse SQL recommendations safely
    set_fact:
      sql_recs: "{{ sql_raw.stdout | default('[]') | from_json }}"

  - name: Initialize SQL report
    set_fact:
      sql_report: []

  - name: Get current SQL tiers
    command: >
      gcloud sql instances describe {{
      item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}
      --project {{ project_id }}
      --format="value(settings.tier)"
    register: sql_current_raw
    loop: "{{ sql_recs }}"
    changed_when: false
    when:
      - item.content.operationGroups is defined
      - item.content.operationGroups | length > 0
      - item.content.operationGroups[0].operations is defined
      - item.content.operationGroups[0].operations | length > 0
      - item.content.operationGroups[0].operations[0].value is defined
      - item.content.operationGroups[0].operations[0].value is mapping
      - item.content.operationGroups[0].operations[0].value.settings is defined
      - item.content.operationGroups[0].operations[0].value.settings.tier is defined

  - name: Evaluate and append downsize SQL
    loop: "{{ sql_current_raw.results | default([]) }}"
    loop_control:
      index_var: idx
    vars:
      sql_instance: "{{ item.item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_tier: "{{ item.item.content.operationGroups[0].operations[0].value.settings.tier }}"
      current_tier: "{{ item.stdout }}"
      current_cpu: "{{ current_tier.split('-')[2] | int }}"
      target_cpu: "{{ target_tier.split('-')[2] | int }}"
    set_fact:
      sql_report: "{{ sql_report + [ {
        'id': 'SQL-' ~ (idx + 1),
        'instance': sql_instance,
        'current': current_tier,
        'suggested': target_tier
      } ] }}"
    when:
      - item.stdout is defined
      - target_cpu < current_cpu



  ###############################################################
  # SAVE ARTIFACTS
  ###############################################################

  - name: Save VM report artifact
    copy:
      content: "{{ vm_report | to_nice_json }}"
      dest: "/runner/artifacts/vm_report.json"

  - name: Save SQL report artifact
    copy:
      content: "{{ sql_report | to_nice_json }}"
      dest: "/runner/artifacts/sql_report.json"

  - name: Save combined report
    copy:
      content: >
        {{
          {
            "vm": vm_report,
            "sql": sql_report
          } | to_nice_json
        }}
      dest: "/runner/artifacts/low_usage_report.json"


  ###############################################################
  # FORMAT TEAMS MESSAGE
  ###############################################################

  - name: Build Teams message
    set_fact:
      teams_message: |
        🔎 GCP LOW USAGE REPORT
        Project : {{ project_id }}

        === VM DOWNSIZE RECOMMENDATIONS ===
        {% if vm_report | length == 0 %}
        No VM downsize recommendations.
        {% else %}
        {% for v in vm_report %}
        [{{ v.id }}]
        Instance : {{ v.instance }}
        Current  : {{ v.current }}
        Suggested: {{ v.suggested }}

        {% endfor %}
        {% endif %}

        === CLOUD SQL DOWNSIZE RECOMMENDATIONS ===
        {% if sql_report | length == 0 %}
        No Cloud SQL downsize recommendations.
        {% else %}
        {% for s in sql_report %}
        [{{ s.id }}]
        Instance : {{ s.instance }}
        Current  : {{ s.current }}
        Suggested: {{ s.suggested }}

        {% endfor %}
        {% endif %}

        NEXT ACTION:
        • Launch "Remediate Low Usage - VM"
        • Launch "Remediate Low Usage - Cloud SQL"

  ###############################################################
  # SEND TO TEAMS
  ###############################################################

  - name: Send report to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: "{{ teams_message }}"
