- hosts: localhost
  gather_facts: false

  vars:
    # =========================
    # PROJECT
    # =========================
    project_id: "joey-preprod-project"

    # =========================
    # RECOMMENDERS (VALID VIA API)
    # =========================
    recommenders:
      - google.compute.image.IdleResourceRecommender
      - google.compute.disk.IdleResourceRecommender
      - google.compute.instance.MachineTypeRecommender
      - google.compute.instanceAvailability.Recommender
      - google.compute.firewall.SecurityRecommender
      - google.iam.policy.Recommender
      - google.container.security.Recommender

    # =========================
    # CATEGORY MAPPING (VALID)
    # =========================
    recommender_category_map:
      google.compute.image.IdleResourceRecommender: COST
      google.compute.disk.IdleResourceRecommender: COST
      google.compute.instance.MachineTypeRecommender: PERFORMANCE
      google.compute.instanceAvailability.Recommender: RELIABILITY
      google.compute.firewall.SecurityRecommender: SECURITY
      google.iam.policy.Recommender: SECURITY
      google.container.security.Recommender: SECURITY

    # =========================
    # TEAMS (POWER AUTOMATE)
    # =========================
    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/94a679db1cd3403e82e75a8e1f0de0c7/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=A0nYXR8b0pMuPINueyCynuAFw_VhCBR8sCticsENRlU"

  tasks:

  # =========================
  # AUTH
  # =========================
  - name: Write GCP service account
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Activate GCP auth
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  # =========================
  # LOCATIONS
  # =========================
  #- name: Get zones
  #  command: gcloud compute zones list --project {{ project_id }} --format="value(name)"
  #  register: zones
  #  changed_when: false
  # locations: "{{ ['global'] + zones.stdout_lines }}"
  - name: Build locations
    set_fact:   
      locations: "{{ ['global'] }}"
  # =========================
  # RUN RECOMMENDERS
  # =========================
  - name: Run recommender API
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ item.0 }}
      --recommender {{ item.1 }}
      --format=json
    loop: "{{ locations | product(recommenders) | list }}"
    register: rec_calls
    changed_when: false
    failed_when: false

  # =========================
  # AGGREGATE (FINAL FIX)
  # =========================
  - name: Aggregate recommendations (FINAL – stable text)
    set_fact:
      all_recommendations: >-
        {{
          all_recommendations | default([]) +
          (
            (item.stdout | from_json)
            | map('combine', {
                'recommender': item.item.1,
                'location': item.item.0,
                'category': recommender_category_map[item.item.1] | default('OTHER'),
                'priority': item.priority | default('MEDIUM'),
  
                'description': (
                  item.description
                  if item.description is defined
                  else (
                    item.content.operationGroups[0].operations[0].value
                    if item.content is defined
                       and item.content.operationGroups is defined
                       and item.content.operationGroups | length > 0
                       and item.content.operationGroups[0].operations | length > 0
                       and item.content.operationGroups[0].operations[0].value is defined
                    else
                      'Recommendation detected'
                  )
                )
              })
            | list
          )
        }}
    loop: "{{ rec_calls.results }}"
    when:
      - item.stdout is defined
      - item.stdout | trim != "[]"


  # =========================
  # BUILD TEAMS MESSAGE (CLEAN)
  # =========================
  - name: Build Teams message
    set_fact:
      teams_message: |
        📊 **GCP Recommender Report**
        Project : {{ project_id }}
        Time    : {{ lookup('pipe','date "+%Y-%m-%d %H:%M:%S"') }}

        ========================
        SUMMARY
        ========================
        Total        : {{ all_recommendations | length }}
        💰 Cost        : {{ all_recommendations | selectattr('category','equalto','COST') | list | length }}
        🚀 Performance : {{ all_recommendations | selectattr('category','equalto','PERFORMANCE') | list | length }}
        🛡️ Security    : {{ all_recommendations | selectattr('category','equalto','SECURITY') | list | length }}
        🧱 Reliability : {{ all_recommendations | selectattr('category','equalto','RELIABILITY') | list | length }}

        ========================
        TOP 5 COST
        ========================
        {% for r in (all_recommendations | selectattr('category','equalto','COST') | list)[:5] %}
        • 💸 {{ r.location }} → {{ r.description }}
        {% else %}
        • No cost recommendations
        {% endfor %}

        ========================
        TOP 3 PERFORMANCE
        ========================
        {% for r in (all_recommendations | selectattr('category','equalto','PERFORMANCE') | list)[:3] %}
        • ⚡ {{ r.location }} → {{ r.description }}
        {% else %}
        • No performance recommendations
        {% endfor %}

  # =========================
  # SEND TO TEAMS
  # =========================
  - name: Send to Microsoft Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      headers:
        Content-Type: application/json
      body_format: json
      body:
        text: "{{ teams_message }}"
      status_code: [200, 202]
