- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    locations:
      - global
      - asia-southeast2-a
      - asia-southeast2

    recommenders:
      # COST
      - google.compute.image.IdleResourceRecommender
      - google.compute.disk.IdleResourceRecommender
      # PERFORMANCE
      - google.compute.instance.MachineTypeRecommender
      - google.cloudsql.instance.PerformanceRecommender
      # SECURITY
      - google.iam.policy.Recommender

    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/b4b10c5f815c4aaa958c92e4ed187886/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=9_QYtd8ZbtUYjegEXrGBnepdWnypMbfzKp01pNdSKC4"

  tasks:
    - name: Write GCP SA
      copy:
        content: "{{ gcp_sa_key }}"
        dest: /tmp/gcp-sa.json
        mode: '0600'

    - name: Auth GCP
      command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
      changed_when: false

    - name: Run recommender API
      command: >
        gcloud recommender recommendations list
        --project {{ project_id }}
        --location {{ item.0 }}
        --recommender {{ item.1 }}
        --format=json
      loop: "{{ locations | product(recommenders) | list }}"
      register: rec_calls
      changed_when: false
      failed_when: false

    - name: Collect results
      set_fact:
        parsed: "{{ parsed | default([]) + (item.stdout | from_json) }}"
      loop: "{{ rec_calls.results }}"
      when: item.stdout is defined and item.stdout | trim != "[]"

    - name: Normalize recommendations (FINAL)
      set_fact:
        all_recommendations: "{{ all_recommendations | default([]) + [ rec_item ] }}"
      vars:
        rec_item:
          id: "{{ rec.name.split('/')[-1] }}"
          location: "{{ rec.name.split('/locations/')[1].split('/')[0] }}"
          category: "{{ rec.primaryImpact.category | default('OTHER') }}"
          resource: >-
            {{
              rec.content.operationGroups[0].operations[0].resource.split('/')[-1]
              if rec.content is defined
              else 'N/A'
            }}
          action: >-
            {{
              'resize_vm'
              if rec.name is search('MachineTypeRecommender')
              else
              'delete_image'
              if rec.name is search('image')
              else
              'update_iam'
              if rec.name is search('iam.policy')
              else
              'ignore'
            }}
          suggestion: "{{ rec.description | default('N/A') }}"
      loop: "{{ parsed }}"
      loop_control:
        loop_var: rec

    - name: Send data to Power Automate
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          project_id: "{{ project_id }}"
          recommendations: "{{ all_recommendations }}"
