- name: GCP Recommender (All Locations) → Teams
  hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"

    # =========================
    # RECOMMENDERS
    # =========================
    recommenders:
      - google.compute.image.IdleResourceRecommender
      - google.compute.disk.IdleResourceRecommender
      - google.compute.instance.MachineTypeRecommender
      - google.compute.instanceAvailability.Recommender
      - google.compute.firewall.SecurityRecommender
      - google.iam.policy.Recommender
      - google.container.security.Recommender

    # =========================
    # TEAMS WEBHOOK (HARDCODE)
    # =========================
    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com/....sig=XXXXX"

  tasks:

  # =========================
  # AUTH GCP
  # =========================
  - name: Activate GCP service account
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  # =========================
  # DISCOVER ALL ZONES (DYNAMIC)
  # =========================
  - name: Get all GCP zones
    command: gcloud compute zones list --project {{ project_id }} --format="value(name)"
    register: zone_list
    changed_when: false

  - name: Build location list (global + zones)
    set_fact:
      locations: "{{ ['global'] + zone_list.stdout_lines }}"

  # =========================
  # RUN RECOMMENDERS (ALL LOCATIONS)
  # =========================
  - name: Run GCP Recommenders dynamically
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ item.0 }}
      --recommender {{ item.1 }}
      --format=json
    loop: "{{ locations | product(recommenders) | list }}"
    register: recommender_calls
    changed_when: false
    failed_when: false

  # =========================
  # AGGREGATE RESULTS
  # =========================
  - name: Aggregate recommendations
    set_fact:
      all_recommendations: >-
        {{
          all_recommendations | default([]) +
          (
            (item.stdout | default('[]') | from_json)
            | map('combine', { 'location': item.item.0 })
            | list
          )
        }}
    loop: "{{ recommender_calls.results }}"
    when:
      - item.stdout is defined
      - item.stdout | trim != "[]"

  # =========================
  # BUILD TEAMS MESSAGE
  # =========================
  - name: Build Teams message
    set_fact:
      teams_message: |
        🔍 GCP Recommender Report
        Project : {{ project_id }}
        Time    : {{ lookup('pipe','date "+%Y-%m-%d %H:%M:%S"') }}

        ========================
        SUMMARY
        ========================
        Total Findings : {{ all_recommendations | length }}

        ========================
        TOP 5 FINDINGS
        ========================
        {% for r in all_recommendations[:5] %}
        - ({{ r.location }}) {{ r.description | default('No description') }}
        {% endfor %}

  # =========================
  # SEND TO TEAMS
  # =========================
  - name: Send message to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      headers:
        Content-Type: application/json
      body_format: json
      body:
        text: "{{ teams_message | trim }}"
      status_code: [200, 202]

