- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"

    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/7c04326d37a64089badfcd62f0176737/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=8PTg2NuHVi98-k2cTNCYG6AVuw_5e-X_UFYsbtzlEog"   # GANTI webhook kamu

  tasks:

  ###############################################################
  # AUTHENTICATION
  ###############################################################

  - name: Write GCP Service Account JSON
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate to GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # VM MACHINE TYPE RECOMMENDATIONS
  ###############################################################

  - name: Get VM MachineType recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ zone }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_raw
    changed_when: false
    failed_when: false

  - name: Parse VM recommendations safely
    set_fact:
      vm_recs: "{{ vm_raw.stdout | from_json }}"
    when:
      - vm_raw.stdout is defined
      - vm_raw.stdout | length > 0

  - name: Initialize VM report
    set_fact:
      vm_report: []

  - name: Process VM recommendations (Downsize only)
    block:
  
      - name: Set VM variables
        set_fact:
          instance_name: "{{ item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
          target_machine_type: "{{ item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1] }}"
  
      - name: Get current VM machine type
        command: >
          gcloud compute instances describe {{ instance_name }}
          --zone {{ zone }}
          --project {{ project_id }}
          --format="value(machineType)"
        register: current_vm
        changed_when: false
  
      - name: Extract VM CPU info
        set_fact:
          current_machine_type: "{{ current_vm.stdout.split('/')[-1] }}"
          current_cpu: "{{ current_vm.stdout.split('/')[-1].split('-')[-1] | int }}"
          target_cpu: "{{ target_machine_type.split('-')[-1] | int }}"
  
      - name: Validate CPU parsing
        fail:
          msg: "Failed to parse CPU from machine type"
        when: current_cpu is not defined or target_cpu is not defined
  
      - name: Append only downsize VM
        set_fact:
          vm_report: "{{ vm_report + [ {
            'id': 'VM-' ~ (idx + 1),
            'instance': instance_name,
            'current': current_machine_type,
            'suggested': target_machine_type
          } ] }}"
        when: target_cpu < current_cpu
  
    loop: "{{ vm_recs | default([]) }}"
    loop_control:
      index_var: idx


  ###############################################################
  # CLOUD SQL PERFORMANCE RECOMMENDATIONS
  ###############################################################

  - name: Get Cloud SQL recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ region }}
      --recommender google.cloudsql.instance.PerformanceRecommender
      --format=json
    register: sql_raw
    changed_when: false
    failed_when: false

  - name: Parse SQL recommendations safely
    set_fact:
      sql_recs: "{{ sql_raw.stdout | from_json }}"
    when:
      - sql_raw.stdout is defined
      - sql_raw.stdout | length > 0

  - name: Initialize SQL report
    set_fact:
      sql_report: []

  - name: Process SQL recommendations (Downsize only)
    loop: "{{ sql_recs | default([]) }}"
    loop_control:
      index_var: idx
    vars:
      sql_instance: "{{ item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}"
      target_tier: "{{ item.content.operationGroups[0].operations[0].value.settings.tier }}"
    block:

      - name: Get current SQL tier
        command: >
          gcloud sql instances describe {{ sql_instance }}
          --project {{ project_id }}
          --format="value(settings.tier)"
        register: current_sql
        changed_when: false

      - name: Extract SQL CPU info
        set_fact:
          current_tier: "{{ current_sql.stdout }}"
          current_cpu: "{{ current_sql.stdout.split('-')[2] | int }}"
          target_cpu: "{{ target_tier.split('-')[2] | int }}"

      - name: Append only downsize SQL
        set_fact:
          sql_report: "{{ sql_report + [ {
            'id': 'SQL-' ~ (idx + 1),
            'instance': sql_instance,
            'current': current_tier,
            'suggested': target_tier
          } ] }}"
        when: target_cpu < current_cpu

  ###############################################################
  # SAVE ARTIFACTS
  ###############################################################

  - name: Save VM report artifact
    copy:
      content: "{{ vm_report | to_nice_json }}"
      dest: "/runner/artifacts/vm_report.json"

  - name: Save SQL report artifact
    copy:
      content: "{{ sql_report | to_nice_json }}"
      dest: "/runner/artifacts/sql_report.json"

  ###############################################################
  # FORMAT TEAMS MESSAGE
  ###############################################################

  - name: Build Teams message
    set_fact:
      teams_message: |
        GCP LOW USAGE REPORT
        Project : {{ project_id }}

        === VM DOWNSIZE RECOMMENDATIONS ===
        {% if vm_report | length == 0 %}
        No VM downsize recommendations.
        {% else %}
        {% for v in vm_report %}
        [{{ v.id }}]
        Instance : {{ v.instance }}
        Current  : {{ v.current }}
        Suggested: {{ v.suggested }}

        {% endfor %}
        {% endif %}

        === CLOUD SQL DOWNSIZE RECOMMENDATIONS ===
        {% if sql_report | length == 0 %}
        No Cloud SQL downsize recommendations.
        {% else %}
        {% for s in sql_report %}
        [{{ s.id }}]
        Instance : {{ s.instance }}
        Current  : {{ s.current }}
        Suggested: {{ s.suggested }}

        {% endfor %}
        {% endif %}

        NEXT ACTION:
        • For VM → Launch template "Remediate Low Usage - VM"
        • For Cloud SQL → Launch template "Remediate Low Usage - Cloud SQL"

  ###############################################################
  # SEND TO TEAMS
  ###############################################################

  - name: Send report to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: "{{ teams_message }}"

  - name: Save combined report
    copy:
      content: >
        {{
          {
            "vm": vm_report,
            "sql": sql_report
          } | to_nice_json
        }}
      dest: "/runner/artifacts/low_usage_report.json"
