- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"
    teams_webhook_url: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/4853a33866174df5a29410585f0e9cf5/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=8E44F_-FX_eJN1eLrAYmL-klR-9puxICRAv2IkzV7cA"

  tasks:

  ###############################################################
  # AUTH
  ###############################################################

  - name: Write GCP SA
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Authenticate
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # VM MACHINE TYPE RECOMMENDER (HIGH USAGE = SCALE UP)
  ###############################################################

  - name: Get VM recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ zone }}
      --recommender google.compute.instance.MachineTypeRecommender
      --format=json
    register: vm_raw
    changed_when: false
    failed_when: false

  - name: Parse VM recommendations
    set_fact:
      vm_recs: "{{ vm_raw.stdout | default('[]') | from_json }}"

  - name: Init VM high usage list
    set_fact:
      vm_high: []

  - name: Get current VM machine types
    command: >
      gcloud compute instances describe
      {{ item.content.operationGroups[0].operations[0].resource.split('/')[-1] }}
      --zone {{ zone }}
      --project {{ project_id }}
      --format="value(machineType)"
    register: current_vm
    loop: "{{ vm_recs }}"
    changed_when: false
    failed_when: false

  - name: Append VM scale-up only
    set_fact:
      vm_high: "{{ vm_high + [ {
        'instance': item.item.content.operationGroups[0].operations[0].resource.split('/')[-1],
        'current': item.stdout.split('/')[-1],
        'suggested': item.item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1]
      } ] }}"
    loop: "{{ current_vm.results }}"
    when: >
      item.stdout is defined and
      (
        item.stdout.split('/')[-1].split('-')[-1] | int
      )
      <
      (
        item.item.content.operationGroups[0].operations[0].value.machineType.split('/')[-1] | int
      )

  ###############################################################
  # CLOUD SQL PERFORMANCE RECOMMENDER
  ###############################################################

  - name: Get SQL recommendations
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ region }}
      --recommender google.cloudsql.instance.PerformanceRecommender
      --format=json
    register: sql_raw
    changed_when: false
    failed_when: false

  - name: Parse SQL recommendations
    set_fact:
      sql_recs: "{{ sql_raw.stdout | default('[]') | from_json }}"

  - name: Init SQL high usage list
    set_fact:
      sql_high: []

  - name: Append ACTIVE PERFORMANCE SQL recommendations
    set_fact:
      sql_high: "{{ sql_high + [ {
        'instance': item.content.overview.instanceName,
        'description': item.description,
        'priority': item.priority
      } ] }}"
    loop: "{{ sql_recs }}"
    when:
      - item.primaryImpact is defined
      - item.primaryImpact.category == "PERFORMANCE"
      - item.stateInfo.state == "ACTIVE"
      - item.content.overview.instanceName is defined

  ###############################################################
  # BUILD MESSAGE
  ###############################################################

  - name: Build Teams message
    set_fact:
      teams_message: |
        🚨 GCP HIGH USAGE REPORT
        Project: {{ project_id }}

        === VM SCALE-UP ===
        {% if vm_high | length == 0 %}
        No VM scale-up recommendation.
        {% else %}
        {% for v in vm_high %}
        • {{ v.instance }}
          Current : {{ v.current }}
          Suggested: {{ v.suggested }}

        {% endfor %}
        {% endif %}

        === CLOUD SQL PERFORMANCE ===
        {% if sql_high | length == 0 %}
        No SQL performance recommendation.
        {% else %}
        {% for s in sql_high %}
        • {{ s.instance }}
          Priority: {{ s.priority }}
          {{ s.description }}

        {% endfor %}
        {% endif %}

        Total VM: {{ vm_high | length }}
        Total SQL: {{ sql_high | length }}

  ###############################################################
  # SEND TO TEAMS (Power Automate)
  ###############################################################

  - name: Send to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      body_format: json
      body:
        text: "{{ teams_message }}"
      status_code: 202
