- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"

    recommenders:
      - google.compute.image.IdleResourceRecommender
      - google.compute.disk.IdleResourceRecommender
      - google.compute.instance.MachineTypeRecommender
      - google.compute.instanceAvailability.Recommender
      - google.compute.firewall.SecurityRecommender
      - google.iam.policy.Recommender
      - google.container.security.Recommender

    recommender_category_map:
      google.compute.image.IdleResourceRecommender: COST
      google.compute.disk.IdleResourceRecommender: COST
      google.compute.instance.MachineTypeRecommender: PERFORMANCE
      google.compute.instanceAvailability.Recommender: RELIABILITY
      google.compute.firewall.SecurityRecommender: SECURITY
      google.iam.policy.Recommender: SECURITY
      google.container.security.Recommender: SECURITY

    teams_webhook_url: "HARDCODE_URL_KAMU"

  tasks:

  - name: Write SA key
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: Auth GCP
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  - name: Get zones
    command: gcloud compute zones list --project {{ project_id }} --format="value(name)"
    register: zones
    changed_when: false

  - set_fact:
      locations: "{{ ['global'] + zones.stdout_lines }}"

  - name: Run recommenders
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ item.0 }}
      --recommender {{ item.1 }}
      --format=json
    loop: "{{ locations | product(recommenders) | list }}"
    register: rec_calls
    changed_when: false
    failed_when: false

  - name: Aggregate recommendations (FIXED)
    set_fact:
      all_recommendations: >-
        {{
          all_recommendations | default([]) +
          (
            (item.stdout | default('[]') | from_json)
            | map('combine', {
                'location': item.item.0,
                'recommender': item.item.1,
                'category': recommender_category_map[item.item.1],
                'description': item.description | default(item.content.description | default('No description'))
              })
            | list
          )
        }}
    loop: "{{ rec_calls.results }}"
    when: item.stdout | default('[]') | trim != "[]"

  - name: Build Teams message (FINAL)
    set_fact:
      teams_message: |
        📊 **GCP Recommender Report**
        Project : {{ project_id }}
        Time    : {{ lookup('pipe','date "+%Y-%m-%d %H:%M:%S"') }}

        =========================
        SUMMARY
        =========================
        Total : {{ all_recommendations | length }}
        • Cost        : {{ all_recommendations | selectattr('category','equalto','COST') | list | length }}
        • Performance : {{ all_recommendations | selectattr('category','equalto','PERFORMANCE') | list | length }}
        • Security    : {{ all_recommendations | selectattr('category','equalto','SECURITY') | list | length }}
        • Reliability : {{ all_recommendations | selectattr('category','equalto','RELIABILITY') | list | length }}

        =========================
        TOP 5 COST
        =========================
        {% for r in (all_recommendations | selectattr('category','equalto','COST') | list)[:5] %}
        - 💰 [{{ r.location }}] {{ r.description }}
        {% else %}
        - No COST findings
        {% endfor %}

        =========================
        TOP 3 PERFORMANCE
        =========================
        {% for r in (all_recommendations | selectattr('category','equalto','PERFORMANCE') | list)[:3] %}
        - 🚀 [{{ r.location }}] {{ r.description }}
        {% else %}
        - No PERFORMANCE findings
        {% endfor %}

  - name: Send to Teams
    uri:
      url: "{{ teams_webhook_url }}"
      method: POST
      headers:
        Content-Type: application/json
      body_format: json
      body:
        text: "{{ teams_message }}"
      status_code: [200, 202]
