- hosts: localhost
  gather_facts: true

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"
    power_automate_webhook: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/ae661a2ed7514edcadc59661196aff27/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uB31RGOx6Asj2iDJqF7LtWzOPOKPE5KXhCLg5J-_1Ss"

    locations:
      - "{{ zone }}"
      - "{{ region }}"
      - "global"

    recommenders:
      - id: "google.compute.instance.MachineTypeRecommender"
      - id: "google.cloudsql.instance.PerformanceRecommender"
      - id: "google.compute.instanceGroupManager.MachineTypeRecommender"
      - id: "google.container.cluster.NodePoolRecommender"
      - id: "google.compute.disk.IdleResourceRecommender"
      - id: "google.compute.image.IdleResourceRecommender"   # ✅ NEW

  tasks:

  ###############################################################
  # AUTH
  ###############################################################

  - name: Write SA key
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: GCP Login
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # FETCH RECOMMENDATIONS (ZONE / REGION / GLOBAL SAFE LOOP)
  ###############################################################

  - set_fact:
      raw_recommendations: []

  - name: Fetch from all recommenders and locations
    loop: "{{ recommenders | product(locations) | list }}"
    loop_control:
      loop_var: combo
    vars:
      rec: "{{ combo.0 }}"
      loc: "{{ combo.1 }}"
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ loc }}
      --recommender {{ rec.id }}
      --format=json
    register: rec_out
    changed_when: false
    failed_when: false

  - name: Merge results
    set_fact:
      raw_recommendations: >
        {{
          raw_recommendations +
          (item.stdout | default('[]') | from_json)
        }}
    loop: "{{ rec_out.results }}"

  ###############################################################
  # NORMALIZE OUTPUT
  ###############################################################

  - set_fact:
      recommendations: []

  - name: Normalize COST recommendations (including delete_image)
    loop: "{{ raw_recommendations }}"
    when:
      - item.primaryImpact is defined
      - item.primaryImpact.category == "COST"
    vars:
      operation: "{{ item.content.operationGroups[0].operations[0] }}"
      resource_name: "{{ operation.resource.split('/')[-1] }}"
      action_type: >-
        {% if 'image' in operation.resource %}
        delete_image
        {% elif 'disk' in operation.resource %}
        delete_disk
        {% elif 'instance' in operation.resource %}
        resize_vm
        {% else %}
        optimize_resource
        {% endif %}
      saving_amount: "{{ item.primaryImpact.costProjection.cost.units | default(0) | int }}"
      saving_currency: "{{ item.primaryImpact.costProjection.cost.currencyCode | default('USD') }}"
    set_fact:
      recommendations: "{{ recommendations + [ {
        'action': action_type,
        'resource': resource_name,
        'category': 'COST',
        'suggestion': 'Save cost by applying recommendation to ' ~ resource_name ~ '.',
        'recommender_id': item.name,
        'location': item.name.split('/')[3],
        'estimated_saving': {
          'amount': saving_amount,
          'currency': saving_currency
        }
      } ] }}"

  ###############################################################
  # BUILD FINAL REPORT
  ###############################################################

  - set_fact:
      final_report:
        project: "{{ project_id }}"
        locations: "{{ locations }}"
        generated_at: "{{ ansible_date_time.iso8601 }}"
        summary:
          total_recommendations: "{{ recommendations | length | int }}"
        recommendations: "{{ recommendations }}"

  ###############################################################
  # SEND TO POWER AUTOMATE
  ###############################################################

  - name: Send to Flow
    uri:
      url: "{{ power_automate_webhook }}"
      method: POST
      body_format: json
      body: "{{ final_report }}"
      status_code: [200, 202]
      return_content: yes
    register: flow_response

  - debug:
      var: flow_response
