- hosts: localhost
  gather_facts: true

  vars:
    project_id: "joey-preprod-project"
    zone: "asia-southeast2-a"
    region: "asia-southeast2"
    power_automate_webhook: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/ae661a2ed7514edcadc59661196aff27/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uB31RGOx6Asj2iDJqF7LtWzOPOKPE5KXhCLg5J-_1Ss"

    locations:
      - "{{ zone }}"
      - "{{ region }}"
      - "global"

    recommenders:
      - id: "google.compute.instance.MachineTypeRecommender"
      - id: "google.cloudsql.instance.PerformanceRecommender"
      - id: "google.compute.instanceGroupManager.MachineTypeRecommender"
      - id: "google.container.cluster.NodePoolRecommender"
      - id: "google.compute.disk.IdleResourceRecommender"
      - id: "google.compute.image.IdleResourceRecommender"

  tasks:

  ###############################################################
  # AUTH
  ###############################################################

  - name: Write SA key
    copy:
      content: "{{ gcp_sa_key }}"
      dest: /tmp/gcp-sa.json
      mode: '0600'

  - name: GCP Login
    command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
    changed_when: false

  ###############################################################
  # FETCH RECOMMENDATIONS
  ###############################################################

  - set_fact:
      raw_recommendations: []

  - name: Fetch from all recommenders and locations
    loop: "{{ recommenders | product(locations) | list }}"
    loop_control:
      loop_var: combo
    vars:
      rec: "{{ combo.0 }}"
      loc: "{{ combo.1 }}"
    command: >
      gcloud recommender recommendations list
      --project {{ project_id }}
      --location {{ loc }}
      --recommender {{ rec.id }}
      --format=json
    register: rec_out
    changed_when: false
    failed_when: false

  - name: Merge results
    set_fact:
      raw_recommendations: >
        {{
          raw_recommendations +
          (item.stdout | default('[]') | from_json)
        }}
    loop: "{{ rec_out.results }}"

  ###############################################################
  # NORMALIZE OUTPUT (USD VERSION + SNAPSHOT FIX)
  ###############################################################

  - set_fact:
      recommendations: []

  - name: Normalize COST recommendations
    loop: "{{ raw_recommendations }}"
    when:
      - item.primaryImpact is defined
      - item.primaryImpact.category == "COST"
      - item.primaryImpact.costProjection is defined
      - item.primaryImpact.costProjection.cost is defined
    vars:
      operation: "{{ item.content.operationGroups[0].operations[0] }}"
      resource_full: "{{ operation.resource }}"
      resource_name: "{{ resource_full.split('/')[-1] }}"
  
      action_type: >-
        {% if 'image' in resource_full %}
        delete_image
        {% elif 'disk' in resource_full %}
        delete_disk
        {% elif 'instance' in resource_full %}
        resize_vm
        {% elif 'snapshot' in resource_full %}
        delete_snapshot
        {% else %}
        optimize_resource
        {% endif %}
  
      saving_units: "{{ item.primaryImpact.costProjection.cost.units | default(0) | float }}"
      saving_nanos: "{{ item.primaryImpact.costProjection.cost.nanos | default(0) | float }}"
      saving_amount: "{{ (saving_units + (saving_nanos / 1000000000.0)) | abs | round(2) }}"
      saving_currency: "{{ item.primaryImpact.costProjection.cost.currencyCode | default('USD') }}"
  
      description_clean: >-
        {{
          (item.description
           | regex_replace('\\$[a-zA-Z\\-]+', resource_name))
        }}
  
    set_fact:
      recommendations: "{{ recommendations + [ {
        'action': action_type | trim,
        'resource': resource_name,
        'location': item.name.split('/')[3],
        'estimated_saving': {
          'amount': saving_amount,
          'currency': saving_currency
        },
        'description': description_clean,
        'recommender_id': item.name
      } ] }}"

  ###############################################################
  # TOTAL SAVING
  ###############################################################

  - name: Calculate total saving
    set_fact:
      total_saving: "{{ recommendations | map(attribute='estimated_saving.amount') | sum | round(2) }}"

  ###############################################################
  # BUILD FINAL REPORT
  ###############################################################

  - set_fact:
      final_report:
        project: "{{ project_id }}"
        locations: "{{ locations }}"
        generated_at: "{{ ansible_date_time.iso8601 }}"
        summary:
          total_recommendations: "{{ recommendations | length | int }}"
          total_estimated_saving: "{{ total_saving }}"
          currency: "USD"
        recommendations: "{{ recommendations }}"

  ###############################################################
  # SEND TO POWER AUTOMATE
  ###############################################################

  - name: Send to Flow
    uri:
      url: "{{ power_automate_webhook }}"
      method: POST
      body_format: json
      body: "{{ final_report }}"
      status_code: [200, 202]
    register: flow_response

  - debug:
      var: flow_response
