- hosts: localhost
  gather_facts: false

  vars:
    project_id: "joey-preprod-project"

    cpu_threshold: 0.80
    memory_threshold: 0.80
    disk_threshold: 0.80

    power_automate_webhook: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/9d45c6f7a85443b3b6e177cdbed4593f/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=k_L8OAke-PRu1QeCdN9uajkJlzXq2ZWVXcT7eKnLYpo"

  tasks:

  ##################################################
  # AUTH
  ##################################################

    - name: Write SA key
      copy:
        content: "{{ gcp_sa_key }}"
        dest: /tmp/gcp-sa.json
        mode: '0600'

    - name: Activate service account
      command: gcloud auth activate-service-account --key-file=/tmp/gcp-sa.json
      changed_when: false

  ##################################################
  # GET ALL CLOUDSQL INSTANCES
  ##################################################

    - name: List CloudSQL instances
      command: >
        gcloud sql instances list
        --project {{ project_id }}
        --format="value(name)"
      register: sql_list
      changed_when: false

    - name: Initialize variables
      set_fact:
        instances: "{{ sql_list.stdout_lines }}"
        high_usage_list: []

  ##################################################
  # LOOP PER INSTANCE (SAFE WAY)
  ##################################################

    - name: Process each CloudSQL instance
      include_tasks: check_instance.yml
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance

  ##################################################
  # SEND CONSOLIDATED REPORT
  ##################################################

    - name: Send Teams report if any high usage
      uri:
        url: "{{ power_automate_webhook }}"
        method: POST
        body_format: json
        body:
          project: "{{ project_id }}"
          threshold_percent: 80
          high_instances: "{{ high_usage_list }}"
          message: "CloudSQL Utilization >= 80% Detected"
        status_code: [200, 202]
      when: high_usage_list | length > 0
