- name: Get VM status
  command: >
    gcloud compute instances describe {{ item.resource }}
    --zone {{ item.location }}
    --project {{ project_id }}
    --format="value(status)"
  register: vm_status
  changed_when: false

- name: Stop VM if running
  command: >
    gcloud compute instances stop {{ item.resource }}
    --zone {{ item.location }}
    --project {{ project_id }}
  when: vm_status.stdout == "RUNNING"

- name: Wait until VM stopped
  command: >
    gcloud compute instances describe {{ item.resource }}
    --zone {{ item.location }}
    --project {{ project_id }}
    --format="value(status)"
  register: vm_wait
  until: vm_wait.stdout == "TERMINATED"
  retries: 10
  delay: 15
  changed_when: false

- name: Resize machine type
  command: >
    gcloud compute instances set-machine-type {{ item.resource }}
    --zone {{ item.location }}
    --machine-type {{ item.recommended }}
    --project {{ project_id }}

- name: Start VM
  command: >
    gcloud compute instances start {{ item.resource }}
    --zone {{ item.location }}
    --project {{ project_id }}
