- hosts: localhost
  gather_facts: false

  vars:
    power_automate_webhook: "https://default4d237fc5b1dd42efa9e264887cb44b.21.environment.api.powerplatform.com/..."

  tasks:
    - name: DEBUG incoming vars
      debug:
        var: ansible_eda.event

    - name: Build formatted alert report
      set_fact:
        report:
          title: "🚨 GCP Alert Notification"
          status: "{{ ansible_eda.event.payload.incident.state | upper }}"
          project: "{{ ansible_eda.event.payload.incident.resource.labels.project_id }}"
          instance: "{{ ansible_eda.event.payload.incident.metric.labels.instance_name }}"
          metric: "{{ ansible_eda.event.payload.incident.metric.displayName }}"
          value: "{{ ansible_eda.event.payload.incident.observed_value }}"
          threshold: "{{ ansible_eda.event.payload.incident.threshold_value }}"
          severity: "{{ ansible_eda.event.payload.incident.severity }}"
          summary: "{{ ansible_eda.event.payload.incident.summary }}"
          time_started: "{{ ansible_eda.event.payload.incident.started_at }}"
          link: "{{ ansible_eda.event.payload.incident.url }}"

    - name: Build Teams message
      set_fact:
        teams_payload:
          text: |
            🚨 **GCP Alert Detected**

            **Status**   : {{ report.status }}
            **Project**  : {{ report.project }}
            **Instance** : {{ report.instance }}

            **Metric**   : {{ report.metric }}
            **Value**    : {{ report.value }}
            **Threshold**: {{ report.threshold }}

            **Severity** : {{ report.severity }}

            **Summary**:
            {{ report.summary }}

            🔗 {{ report.link }}

    - name: Send alert to Teams
      uri:
        url: "{{ power_automate_webhook }}"
        method: POST
        body_format: json
        body: "{{ teams_payload }}"
        status_code: [200, 202]

    - name: Debug payload
      debug:
        var: teams_payload
