- name: GCP monitoring listener
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: alert still happening
      condition: incident.state == "open"
      action:
        run_job_template:
          name: rulebook-usecase2-highusage
          organization: Default
          extra_vars:
            event: "{{ event }}"
            alert_status: "OPEN"

    - name: alert resolved
      condition: event.incident.state == "closed"
      action:
        run_job_template:
          name: rulebook-usecase2-highusage
          organization: Default
          extra_vars:
            event: "{{ event }}"
            alert_status: "CLOSED"
