- name: GCP Alert Listener
  hosts: localhost

  sources:
    - google.cloud.pubsub:
        project_id: orms-sta-project
        subscription: cloudsql-alert-sub

  rules:
    - name: Instance CPU High
      condition: event.data.body.incident.state == "open"
      action:
        run_job_template:
          name: hello_world
