- name: GCP monitoring listener
  hosts: localhost

  sources:
    - ansible.eda.process:
        command: python3 gcp_alert_listener.py
        parse_json: true
        restart: true

  rules:
    - name: alert detected
      condition: true
      action:
        debug:
          msg: "{{ event }}"
