- name: GCP monitoring listener
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: alert open (rate limit)
      condition: event.payload.incident.state == "open"
      action:
        run_job_template:
          name: rulebook-usecase2-highusage
          organization: Default
      throttle:
        group_by: "{{ event.payload.incident.incident_id }}"
        seconds: 60

    - name: alert closed (once only)
      condition: event.payload.incident.state == "closed"
      action:
        run_job_template:
          name: rulebook-usecase2-highusage
          organization: Default
      throttle:
        once: "{{ event.payload.incident.incident_id }}-closed"
